obstacle_range: 4.0
raytrace_range: 4.0

footprint: [[-0.25, -0.2], [-0.25, 0.2], [0.25, 0.2], [0.25, -0.2]]
# robot_radius: 0.19

inflation_radius: 1
cost_scaling_factor: 10

map_type: costmap

#% 联合避障模式。
observation_sources: point_cloud_sensor
point_cloud_sensor: {
  sensor_frame: base_link,
  data_type: PointCloud2, 
  topic: /fusion_cloud, 
  expected_update_rate: 30, 
  marking: true, 
  clearing: true,
  min_obstacle_height: -5.0,
  max_obstacle_height: 5.0}


# observation_sources: point_cloud_sensor
# point_cloud_sensor: {
#   sensor_frame: base_footprint,
#   data_type: PointCloud2, 
#   topic: /tof_camera/proj_obstacles, 
#   expected_update_rate: 5, 
#   marking: true, 
#   clearing: true,
#   min_obstacle_height: -5.0,
#   max_obstacle_height: 5.0
# }

# observation_sources: scan
# scan: {
#   sensor_frame: base_footprint,
#   data_type: LaserScan,
#   topic: /scan,
#   marking: true,
#   clearing: true,
#   min_obstacle_height: -5.0,
#   max_obstacle_height: 5.0,
#   expected_update_rate: 10
#   }