obstacle_range: 4.0
raytrace_range: 4.0

# footprint: [[-0.3, -0.25], [-0.3, 0.25], [0.3, 0.25], [0.3, -0.25]]
robot_radius: 0.26

inflation_radius: 0.7
cost_scaling_factor: 10

map_type: costmap

#% 联合避障模式。
observation_sources: laser camera
laser: {
  sensor_frame: base_link,
  data_type: LaserScan, 
  topic: /scan, 
  expected_update_rate: 10, 
  marking: true, 
  clearing: true,
  min_obstacle_height: 0,
  max_obstacle_height: 1
}
camera: {
  sensor_frame: base_link,
  data_type: PointCloud2, 
  topic: /tof_camera/proj_obstacles, 
  expected_update_rate: 10, 
  marking: true, 
  clearing: true,
  min_obstacle_height: 0,
  max_obstacle_height: 1
}

