local_costmap:
  global_frame: rtabmap_odom
  robot_base_frame: base_footprint

  update_frequency: 3.0
  publish_frequency: 3.0

  # static_map: false  #不使用静态地图
  rolling_window: true  #使用滚动地图
  width: 5
  height: 5
  resolution: 0.05
  transform_tolerance: 10.0

  plugins:
  - {name: obstacle_layer,   type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}



